language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - 2.2.0
notifications:
  email:
    recipients:
      - grauwoelfchen@gmail.com
    on_success: change
    on_failure: always
gemfiles:
  - gemfiles/0.0.5.gemfile
  - gemfiles/0.0.6.gemfile
matrix:
  allow_failures:
    - rvm: 1.8.7
